Document: spirv-cross
Title: Debian spirv-cross Manual
Author: <insert document author here>
Abstract: This manual describes what spirv-cross is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spirv-cross/spirv-cross.sgml.gz

Format: postscript
Files: /usr/share/doc/spirv-cross/spirv-cross.ps.gz

Format: text
Files: /usr/share/doc/spirv-cross/spirv-cross.text.gz

Format: HTML
Index: /usr/share/doc/spirv-cross/html/index.html
Files: /usr/share/doc/spirv-cross/html/*.html
